### ISSUE TITLE
Support for drop wizard 0.9.x

### ISSUE THREAD

**Issue by amitjindal** [ToastShaman/dropwizard-auth-jwt#12]
Hi, Thanks a lot for this wonderful library. I have started using this and it works great.

Its probably too early to ask about this but I am really excited about Authorisation features in 0.9-RC2. Any plans to update this for the API changes soon?

Thanks!
Amit

**Comment by kimble** [comment]
Thanks for putting time and energy into this! 

Would you mind pushing the 0.9 support to http://oss.sonatype.org/content/repositories/snapshots ?

**Comment by ToastShaman** [comment]
Of course, you'll find them here: 

https://oss.sonatype.org/content/repositories/snapshots/com/github/toastshaman/dropwizard-auth-jwt/0.9.0-0-SNAPSHOT/

**Comment by kimble** [comment]
Thanks! :-)

**Comment by ToastShaman** [comment]
Just published the new binaries to Maven Central. Thanks @kimble

**Comment by kimble** [comment]
Thanks for merging and pushing binaries to Maven Central!
Have a nice weekend!
