### ISSUE TITLE
Running example code: Error decoding credentials: The token has expired

### ISSUE THREAD

**Issue by peavers** [ToastShaman/dropwizard-auth-jwt#18]
Just building and running the example, using postman and setting the token in the header I'm receiving

```
WARN  [2015-12-05 04:16:09,509] com.github.toastshaman.dropwizard.auth.jwt.JWTAuthFilter: Error decoding credentials: The token has expired
! com.github.toastshaman.dropwizard.auth.jwt.exceptions.TokenExpiredException: The token has expired
```

**Comment by ToastShaman** [comment]
Hi @peavers. Sorry about that, the example actually was generating an expired token to illustrate the ExpiryValidator. I've extended the example and added some more in the Readme. Hopefully this makes things a bit clearer.
