### ISSUE TITLE
Confusion over Principal vs User in Example code

### ISSUE THREAD

**Issue by peavers** [ToastShaman/dropwizard-auth-jwt#19]
Hopefully someone can clarify this a bit for me (I'm new to this so apologies if it's obvious)

In the ExampleAuthenticator class you return an object of type Principal
```Java
        @Override
        public Optional<Principal> authenticate(JsonWebToken token) {

            if ("good-guy".equals(token.claim().subject())) {
                final Principal principal = new Principal() {
                    @Override
                    public String getName() {
                        return "good-guy";
                    }
                };
                return Optional.of(principal);
            }

            return Optional.absent();
        }
```
Yet in SecuredResource example, the check-token is looking for an object of type User
```Java
    @GET
    @Path("/check-token")
    public Map<String, String> get(@Auth User user) {
        return singletonMap("username", user.getUsername());
    }
```
As it never receives this, it throws a null pointer when trying to access user.getUsername. This can easily be fixed by either changing the expected type to Principal
```Java
    public Map<String, String> get(@Auth Principal user) { }
```

Or changing the Authenticator to create a User object instead. What is the correct way here? Does it even matter, or have I completely missed something and got this all wrong? 

Would love some advice/guidance

**Comment by ToastShaman** [comment]
Hi @peavers. You are absolutely right. This was an oversight on my part and using the Principal is the correct thing to do here. See my last commit 572d43494cd8809e2cdf5c82d472563cb5d979c9. Hopefully this makes things a bit clearer.

**Comment by peavers** [comment]
Really appreciate the examples, has made this a lot easier to understand.
