### ISSUE TITLE
Using an object when authenticating

### ISSUE THREAD

**Issue by patrickreck** [ToastShaman/dropwizard-auth-jwt#20]
Am I supposed to store an ID of the user authorizing in the `Principal.getName()` or is it possible to actually store a `User` object?

I've tried to replace the `Principal` with a `User` extending it with little success:
<img width="1057" alt="skaermbillede 2016-02-08 kl 19 37 28" src="https://cloud.githubusercontent.com/assets/2742100/12895198/743f3746-ce9b-11e5-9a10-cc9ad03718cd.png">

Could you enlighten me on how I should be using this?

**Comment by ToastShaman** [comment]
Hi, 

You can use your own `User` object as long as it `extends java.security.Principal`. See my previous commit that uses a `MyUser` object with an additional `getId()` method. It is up to you what information you want to store as part of your `Principal` implementation.

**Comment by situokko** [comment]
Just used it like this and it is working nicely!

**Comment by patrickreck** [comment]
Yep, this is working perfectly fine. Thank you!
