### ISSUE TITLE
audience not supported

### ISSUE THREAD

**Issue by sandlinm** [ToastShaman/dropwizard-auth-jwt#23]
Are you planning on implementing the audience claim? 

https://tools.ietf.org/html/rfc7519#section-4.1.3

**Comment by ToastShaman** [comment]
I am planning on replacing my own JWT implementation with jose4j in the upcoming 1.0 release of Dropwizard. Would that work for you?

**Comment by sandlinm** [comment]
Absolutely ;)...

**Comment by ToastShaman** [comment]
Fixed in release v1.0.0-0 release.
