### ISSUE TITLE
Detect when token has been expired

### ISSUE THREAD

**Issue by situokko** [ToastShaman/dropwizard-auth-jwt#32]
I was using 0.8.x before and there you threw specific TokenExpiredException, however now with 0.5.5 Jose4J this information is hidden within the private fields of InvalidJwtException.

Jose4J 0.6.0 (released week ago) exposes this information via InvalidJwtException.hasExpired(). Would it be possible to change dropwizard-auth-jwt to depend on that 0.6.0 version?

https://bitbucket.org/b_c/jose4j/issues/76/provide-programmatic-access-to-specific

**Comment by situokko** [comment]
I have fixed it here: https://github.com/ToastShaman/dropwizard-auth-jwt/pull/33

**Comment by ToastShaman** [comment]
I've merged #33
