### ISSUE TITLE
Update to dropwizard 8

### ISSUE THREAD

**Issue by MartinSahlen** [ToastShaman/dropwizard-auth-jwt#6]
Have you considered updating to dropwizard 8? Or are you waiting until the release? Anyways, I have made a factory (which is what previously is called a provider) if this could be of interest. The benefit in dropwizard 8 is that it supports chained authentication, meaning that you can use both basic and jwt in the same application. I have added a gist that shows the main parts of my ideas here: https://gist.github.com/MartinSahlen/67540d2963603f714596

**Comment by tzahari** [comment]
Hi Martin,
Dropwizard 0.8.0 was released on Mar 5.
http://dropwizard.io/about/release-notes.html#v0-8-0
BR
Thomas

**Comment by ToastShaman** [comment]
Hi all,

Thank you for the nudge. The gist looks good @MartinSahlen. I'll have a closer look and will base it on that.

Cheers,
Kevin

**Comment by MartinSahlen** [comment]
Ah, just saw that now @tzahari. Looking forward to getting this in maven @ToastShaman :)

**Comment by ToastShaman** [comment]
Hi @MartinSahlen,

Sorry it took me so long to close this issue. Anyhow, I've basically copy pasted your Gist and updated the tests. I've mentioned you in the Readme. Thanks a lot!! 

Let me know if there is anything else I can do to make this better.

**Comment by MartinSahlen** [comment]
Any time! And thanks for the creds! I'll surely let you know, great to have this on 0.8 as well :)
