### ISSUE TITLE
Expired Token produces InternalServerError

### ISSUE THREAD

**Issue by McPringle** [ToastShaman/dropwizard-auth-jwt#9]
An expired token leads into an InternalServerError. That is really bad because it will result in HTTP status code 500 and the client thinks the failure is on the server side. Returning a 401 Unauthorized is much better.

JWTAuthFactory: line 115 to 117

**Comment by MartinSahlen** [comment]
Yes, this is indeed not a good design choice. As this obviously is an error induced by a bad request, it should definitely return a response in the 4xx range, and the most appropriate and generic is a 401 as you state @McPringle.

**Comment by ToastShaman** [comment]
Yes, totally agree @McPringle. 

Can you give this a try and see whether that works for you?

I've applied the fix for the 0.8.x branch.

**Comment by McPringle** [comment]
Hi @ToastShaman 

Your fix works perfectly! Thanks for your amazing fast response!
